/// Flutter icons CustomIcon
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const String? _kFontPkg = null;

  static const IconData blowing_snow = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dust = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData freezing_fog = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frog = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gale = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grey = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heavy_frog = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heavy_sandstorm = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mostly_night = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mostly_sunny = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData night = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pm2_5 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sand = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData showers = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sleet = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow_showers = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData storm = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sunny = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thundershower = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tornado = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData typhoon = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drizzle = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
